name: lince_time
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0 # Asegúrate de usar una versión compatible con tu SDK
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  change_app_package_name: ^1.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  google_sign_in: ^6.2.2
  mailer: ^6.2.0
  firebase_messaging: ^15.1.5
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  flutter_local_notifications: ^18.0.1
  twilio_flutter: ^0.9.0
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  flutter_sms: ^2.3.3
  flutter_timezone: ^3.0.1
  timezone: ^0.10.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  file_picker: ^8.1.4

  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Asegúrate de que la ruta es correcta
    - assets/icons/
    - assets/fonts/
    - assets/config/serviceAccountKey.json
  