// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRpS6PWIJE6kk0YoPlXSgGKQePdt-6GEQ',
    appId: '1:419688568194:web:443b8e4bb7bb1d149d2b9b',
    messagingSenderId: '419688568194',
    projectId: 'cafeteria2024-b355c',
    authDomain: 'cafeteria2024-b355c.firebaseapp.com',
    storageBucket: 'cafeteria2024-b355c.appspot.com',
    measurementId: 'G-R52P03QT5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ce5F2yisWCFa1UKZUKhpDdPFfdBKQHY',
    appId: '1:419688568194:android:60c2eb51d9313ab99d2b9b',
    messagingSenderId: '419688568194',
    projectId: 'cafeteria2024-b355c',
    storageBucket: 'cafeteria2024-b355c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA408ARKBeHTjBKem8duG-yY0-Nq-_2ltQ',
    appId: '1:419688568194:ios:066584e26bfc14279d2b9b',
    messagingSenderId: '419688568194',
    projectId: 'cafeteria2024-b355c',
    storageBucket: 'cafeteria2024-b355c.appspot.com',
    iosBundleId: 'cafeteria.lj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRpS6PWIJE6kk0YoPlXSgGKQePdt-6GEQ',
    appId: '1:419688568194:web:ff1d6287821471949d2b9b',
    messagingSenderId: '419688568194',
    projectId: 'cafeteria2024-b355c',
    authDomain: 'cafeteria2024-b355c.firebaseapp.com',
    storageBucket: 'cafeteria2024-b355c.appspot.com',
    measurementId: 'G-0YWPXPLGQN',
  );
}
